Use ag instead of ack

diff --git a/init b/init
--- a/init
+++ b/init
@@ -25,14 +25,14 @@ export DOTFILES=$HOME/.dotfiles
 sudo -v
 
 # Preinstall
-if ! hash zsh hub ack 2>/dev/null ; then
+if ! hash zsh hub ag 2>/dev/null ; then
   if [ `uname` == 'Darwin' ]; then
     ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
-    brew install zsh hub ack
+    brew install zsh hub the_silver_searcher
   elif [ `uname` == 'Linux' ]; then
-    sudo apt-get install zsh hub ack-grep
+    sudo apt-get install zsh hub silversearcher-ag
   else
-    error "zsh, hub and ack is required"
+    error "zsh, hub and ag is required"
     exit
   fi
 fi
@@ -66,7 +66,6 @@ fi
 ln -fs $DOTFILES/.aliases      $HOME/.aliases
 ln -fs $DOTFILES/.exports      $HOME/.exports
 ln -fs $DOTFILES/.gitconfig    $HOME/.gitconfig
-ln -fs $DOTFILES/.ackrc        $HOME/.ackrc
 ln -fs $DOTFILES/.vimrc        $HOME/.vimrc
 ln -fs $DOTFILES/.zshrc        $HOME/.zshrc
 ln -fs $DOTFILES/.hyperterm.js $HOME/.hyperterm.js
